### ISSUE TITLE
Reduce verbosity by default, making piping into other CLI tools easier.

### ISSUE THREAD

**Issue by MikeCostello** [ricanontherun/rabbit-tail#5]
Maybe have a log level so that just the payload could be output. This would be helpful when piping the output to a json processor.

**Comment by ricanontherun** [comment]
Perhaps I can leverage the --verbose flag for this. If omitted, no additional output will printed, just the AMQP payload. If the --verbose flag is provided, I'll print with timestamps, and log levels.

Thoughts?
